//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Repositories.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FrameworkEntities : DbContext, IFrameworkEntities
    {
        public FrameworkEntities()
            : base("name=FrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SisListaPermiso> SisListaPermisoes { get; set; }
        public virtual DbSet<SisMenu> SisMenus { get; set; }
        public virtual DbSet<SisOperacione> SisOperaciones { get; set; }
        public virtual DbSet<SisRol> SisRols { get; set; }
        public virtual DbSet<SisUsuario> SisUsuarios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
