//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SisOperacione
    {
        public SisOperacione()
        {
            this.SisListaPermisoes = new HashSet<SisListaPermiso>();
        }
    
        public int opId { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public short Orden { get; set; }
    
        public virtual ICollection<SisListaPermiso> SisListaPermisoes { get; set; }
    }
}
