//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SisUsuario
    {
        public SisUsuario()
        {
            this.SisRols = new HashSet<SisRol>();
        }
    
        public int usuarioId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Mail { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<SisRol> SisRols { get; set; }
    }
}
